version: "3"
services:

  web:
    image : node:boron
    volumes:
      - ./app/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; ./node_modules/.bin/bower install --allow-root; npm run build; npm run dev'
    ports:
        - 3000:3000
    network_mode: "host"
    tty : true