version: "2"
services:
  web:
    image : node:boron
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; ./node_modules/.bin/bower install --allow-root; npm run build; npm run dev'
    ports:
        - 3000:3000
    links :
        - mongo
  mongo:
    image: mongo

    volumes:
        - ./app/data/db:/app/data/db
    ports:
      - "27017:27017"
  mongoexpress:
    image: mongo-express
    links:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - WEB_USER='user'
      - WEB_PASS='pass'
    command: sh -c 'sleep 10 && tini -s -- node app'
