version: "3"
services:
  web:
    image : node:boron
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; ./node_modules/.bin/bower install --allow-root; npm run build; npm run dev'
    ports:
        - 3000:3000
    tty : true
    links :
        - mongo
  mongo:
    image: mongo
    volumes:
        - ./app/data/db:/app/data/db
    ports:
      - "27017:27017"
volumes:
    mydata:
