version: "3"

services:

### nginx Server Container #######################################

  nginx:
    image : nginx
    volumes:
      - ./nginx:/etc/nginx
    expose:
        - '80'
    ports:
        - 80:80
    links :
        - api
        - react

### react.js dev Container #####################################

  react:
    image : node:boron
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm run dev'
    ports:
        - 8080:8080
    links :
        - api

### node.js Server Container ##################################

  api:
    image : node:boron
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm run dev'
    ports:
        - 3000:3000
    links :
        - mysql

### MySQL Container #########################################

  mysql:
    build:
        context: ./mysql
    user: "1000:50"
    environment:
      MYSQL_DATABASE: matchadb
      MYSQL_USER: jwalle
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
          - ./app/data/db:/var/lib/mysql
          - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306


### phpMyAdmin Container ####################################

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
