version: "3"
services:
  web:
    image : node:boron
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; ./node_modules/.bin/bower install --allow-root; npm run build; npm run dev'
    ports:
        - 3000:3000
    links :
        - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: matchadb
      MYSQL_USER: jwalle
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./app/data/db:/var/lib/mysql
    ports:
      - 3306
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
